sudo: false
language: ruby
rvm:
  - 2.2.4
env:
  global:
    - CC_TEST_REPORTER_ID=45175f9e10f6665368de72e4049a8c258ac65dacd4704f8cf1e71a5a87835498

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
